name: Build and Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v -o reverse-proxy-inspector ./...

    - name: Test
      run: go test -v ./...

    - name: Get version
      id: get_version
      run: echo "VERSION=$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create v${{ steps.get_version.outputs.VERSION }} \
          --title "Release ${{ steps.get_version.outputs.VERSION }}" \
          --notes "Automated release for version ${{ steps.get_version.outputs.VERSION }}" \
          ./reverse-proxy-inspector

